### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by DragonHeart69**
custom css misplaced

### CODE REVIEW

**Comment by loganmarchione** [comment]
@DragonHeart69 we should probably also remove the style include a few lines after this change, right?

**Comment by DragonHeart69** [comment]
@loganmarchione Yes, sorry, this is my very first contribution to a project, so it will be a bit of a search. It has been modified.
Can I also look to incorporate a dark-mode ?

**Comment by loganmarchione** [comment]
@DragonHeart69 thanks! You'll need to pull down the 0.0.3 container to see the changes. Also, since the location of the `style` tag moved, you'll need to remove the `style` tag from the custom CSS file. I updated the [documentation](https://github.com/loganmarchione/docker-php-startpage/blob/master/FEATURES.md#custom-css) to match.

Yes, if you know CSS (which I clearly don't lol) feel free to submit a PR about dark mode. If you're going to look into this, I would definitely want this to be switch-able by the user (either through the config file or through the web front-end or though the CSS system preferences). There appears to be a third-party [repo](https://vinorodrigues.github.io/bootstrap-dark-5/) to do this, I might look into this as well.

**Comment by DragonHeart69** [comment]
Best,

I already have a prototype on [my branch darkmode](https://github.com/DragonHeart69/docker-php-startpage/tree/darkmode) (screenshot in readme). However, this can only be obtained by placing the custom css in the folder. I can look into it further, but I would have liked to have all your opinion before proceeding. Personally, I'm not a fan of bootstrap, so I won't really be implimenting bootstrap dark. The bootstrap file will be fully loaded, full of unnecessary stuff.

A button in the UI should work, even with automatic detection of system settings.

**Comment by loganmarchione** [comment]
@DragonHeart69 I like what you have so far! I also like that it's simple CSS that can be copy/pasted into the `user_includes` directory (so no changes inside the container are necessary).

I went with Bootstrap because I know almost nothing about CSS/JS and Bootstrap was able to get me up and running in no time (and it was available on Packagist). I know it adds extra stuff, but if it's loading locally (not from a CDN), I figure it's not a huge hit 🤷‍♂️.

If you get to a point where you have a version of darkmode style.css that you're happy with, I can definitely put it into a `darkmode.md` file and reference your GitHub user to give credit, or if you want to keep darkmode on a fork of your own, I can just point people right to your implementation.

**Pull request merged**
