### PR TITLE
add a centered  header

### PR DESCRIPTION
**Pull request by DragonHeart69**
2022-04-12 15_49_06-DragonHeart's Home DashBoard - Vivaldi
I like to have my search engine always at hand. But to put it right by the links is not really a pretty sight. With this addition, it can be centered.

### CODE REVIEW

**Comment by DragonHeart69** [comment]
now it's work fine for me

**Comment by loganmarchione** [comment]
@DragonHeart69 this broke with hamburger menu when resizing the window, going to keep your changes but try to fix this breakage

**Comment by DragonHeart69** [comment]
Hmmm, weird, I'll check it again tomorrow, this can indeed not be the intention.

**Comment by loganmarchione** [comment]
I just pushed code to master that I believe fixes it on desktop and mobile.

**Comment by DragonHeart69** [comment]
Indeed, this solves the problem. I had something ready myself before I saw your post. I just closed this one, it looks like yours is even better :)

PS: Do you want to change the screenshot of the darkmode to your test setup please ?

**Pull request merged**
